globals:
  seed: 1213
  device: cuda
  output_dir: output
  num_epochs: 50
  main_metric: epoch_source_acc
  minimize_metric: False

datasets:
  name: digits

loader:
  params:
    train:
      batch_size: 128
      shuffle: True
      num_workers: 8
    valid:
      batch_size: 128
      shuffle: False
      num_workers: 8

model:
  name: cnn

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name:

runner: dann

callbacks:
  - name: DANNClassificationAccuracy
    params:
      output_key: logits
      prefixes:
        0: source_acc
        1: target_acc

  - name: DANNDomainAUC
    params:
      output_key: logits
      prefix: domain_auc
