globals:
  seed: 1213
  device: cuda
  output_dir: output
  num_epochs: 50
  main_metric: epoch_balanced_mcc
  minimize_metric: False

datasets:
  name: vsb

loader:
  params:
    train:
      batch_size: 256
      shuffle: True
      num_workers: 8
    valid:
      batch_size: 512
      shuffle: False
      num_workers: 8

model:
  name: rnn
  params:
    warmup: True

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name:

runner: dann

callbacks:
  - name: MatthewsCorrelationCoeficient
    params:
      output_key: logits
      prefix: "mcc"

  - name: DANNDomainAUC
    params:
      output_key: logits
      prefix: domain_auc

  - name: AUCBalancedMCC
    params:
      output_key: logits
      prefix: balanced_mcc
